import threading

lcd_lock = threading.Lock()
dht_lock = threading.Lock()
matrix_lock = threading.Lock()
buzzer_lock = threading.Lock()
lightsensor_lock = threading.Lock()
ledmatrix_lock = threading.Lock()
vibration_lock = threading.Lock()
relay_lock = threading.Lock()
segment_lock = threading.Lock()
ultrasonicsensor_lock = threading.Lock()

touchsensor_lock = threading.Lock()
joystick_lock = threading.Lock()
tiltsensor_lock = threading.Lock()
soundsensor_lock = threading.Lock()
irsensor_lock = threading.Lock()
nfcsensor_lock = threading.Lock()
servo_lock = threading.Lock()
stepmotor_lock = threading.Lock()
